# Generated by Django 3.0.2 on 2020-01-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bareNuclei',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='blandChromatin',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='clumpThickness',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marginalAdhesion',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mitoses',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='normalNucleoli',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='singleEpithelialCellSize',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uniformityCellShape',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uniformityCellSize',
            field=models.FloatField(null=True),
        ),
    ]
