# Generated by Django 3.0.2 on 2020-01-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0002_auto_20200121_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
    ]
