# Generated by Django 3.0.2 on 2020-01-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0003_auto_20200121_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
